# Node CircleCI 2.0 configuration file to DTA cloud 2.0

version: 2
jobs:

  # DEPLOY-STAGING JOB
  # installing dependencies, building assets and test
  test:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout                 # get the files from the repo (why would you ever not want the files????)
      - restore_cache:
          keys:
            - v1-node-cache-{{ checksum "yarn.lock" }}
      - run: yarn install         # duh
      - save_cache:
          key: v1-node-cache-{{ checksum "yarn.lock" }}
          paths:
              - node_modules
      - run: yarn build       # build all packages
      - run: yarn test            # run all tests



# OUR WORKFLOW
# this is where we orchestrate our jobs
workflows:
  version: 2
  testing:
    jobs:
      - test  # run test
